package io.tekniq.jdbc

import io.kotest.assertions.throwables.shouldThrow
import io.kotest.core.spec.style.DescribeSpec
import io.kotest.matchers.nulls.shouldNotBeNull
import io.kotest.matchers.shouldBe
import java.sql.Connection
import java.sql.PreparedStatement
import java.sql.SQLException
import javax.sql.DataSource

/**
 * Regression coverage for the defects fixed in 0.23.0. HSQLDB cannot reveal resource leaks on its
 * own -- it ignores `closeOnCompletion`, keeps statements open when a connection closes, and serves
 * rows from a closed cursor -- so statement lifetime is asserted through [TrackingConnection]
 * rather than inferred from a query succeeding.
 */
object TqJdbcRegressionSpec : DescribeSpec({
    val shared = TqSingleConnectionDataSource("jdbc:hsqldb:mem:tekniqregress", "sa", "").connection.apply {
        createStatement().use { stmt ->
            stmt.execute("DROP TABLE regress IF EXISTS")
            stmt.execute("CREATE TABLE regress (id INTEGER, name VARCHAR(100))")
            stmt.execute("INSERT INTO regress VALUES(1, 'Foo')")
            stmt.execute("INSERT INTO regress VALUES(2, 'a:b')")
            stmt.execute("INSERT INTO regress VALUES(3, 'Bar')")
            stmt.execute("DROP TABLE keyed IF EXISTS")
            stmt.execute("CREATE TABLE keyed (id INTEGER GENERATED BY DEFAULT AS IDENTITY, name VARCHAR(50))")
        }
    }

    describe("named parameter parsing") {
        // The old regex rewrote any :word anywhere, silently corrupting reads and writes.
        it("leaves a colon inside a string literal alone") {
            parseNamedParameters("SELECT * FROM t WHERE name = 'a:b'") shouldBe
                ("SELECT * FROM t WHERE name = 'a:b'" to emptyList())
        }

        it("leaves a postgres cast alone") {
            parseNamedParameters("SELECT id::text FROM t") shouldBe ("SELECT id::text FROM t" to emptyList())
        }

        it("leaves comments alone") {
            parseNamedParameters("SELECT 1 -- :note\n/* :block */") shouldBe
                ("SELECT 1 -- :note\n/* :block */" to emptyList())
        }

        it("still rewrites real placeholders, including alongside a literal and a cast") {
            parseNamedParameters("SELECT id::text FROM t WHERE a=:x AND b='c:d' AND e=:y") shouldBe
                ("SELECT id::text FROM t WHERE a=? AND b='c:d' AND e=?" to listOf("x", "y"))
        }

        it("repeats a duplicated name once per occurrence") {
            parseNamedParameters("WHERE a=:x OR b=:x") shouldBe ("WHERE a=? OR b=?" to listOf("x", "x"))
        }

        it("handles an escaped quote inside a literal") {
            parseNamedParameters("WHERE a='it''s :not' AND b=:real") shouldBe
                ("WHERE a='it''s :not' AND b=?" to listOf("real"))
        }
    }

    describe("named parameter binding") {
        it("selects through a literal containing a colon") {
            shared.selectFirst("SELECT id FROM regress WHERE name = 'a:b'") { getInt("id") } shouldBe 2
        }

        it("binds named parameters from a map") {
            shared.selectFirst("SELECT name FROM regress WHERE id = :id", mapOf("id" to 3)) {
                getString("name")
            } shouldBe "Bar"
        }

        // Previously a missing key silently bound null, so an update quietly matched no rows.
        it("fails loudly when a named parameter has no value") {
            shouldThrow<IllegalArgumentException> {
                shared.selectFirst("SELECT id FROM regress WHERE name = :name", mapOf("wrong" to "x")) {
                    getInt("id")
                }
            }
        }

        it("does not treat a lone map as named values when the sql has no placeholders") {
            shared.selectFirst("SELECT id FROM regress WHERE id = 1") { getInt("id") } shouldBe 1
        }
    }

    describe("statement and cursor lifetime") {
        it("closes the statement when a stream is fully drained") {
            val conn = TrackingConnection(shared)
            conn.stream("SELECT id FROM regress") { getInt("id") }.toList() shouldBe listOf(1, 2, 3)
            conn.allClosed() shouldBe true
        }

        // Empty results never closed anything: hasMore was set in the constructor but close() only
        // ever ran from next().
        it("closes the statement for an empty result set") {
            val conn = TrackingConnection(shared)
            conn.stream("SELECT id FROM regress WHERE id = 999") { getInt("id") }.toList() shouldBe emptyList()
            conn.allClosed() shouldBe true
        }

        // Partial consumption leaked a statement per call and close() was unreachable, because the
        // declared return type was Sequence and the class was not AutoCloseable.
        it("closes the statement when a partially consumed stream is used") {
            val conn = TrackingConnection(shared)
            conn.stream("SELECT id FROM regress") { getInt("id") }.use { it.first() } shouldBe 1
            conn.allClosed() shouldBe true
        }

        it("closes the statement for the eager select") {
            val conn = TrackingConnection(shared)
            conn.select("SELECT id FROM regress") { getInt("id") } shouldBe listOf(1, 2, 3)
            conn.allClosed() shouldBe true
        }

        // Re-iterating advanced the shared cursor, silently dropping rows.
        it("refuses to iterate a stream twice") {
            val conn = TrackingConnection(shared)
            conn.stream("SELECT id FROM regress") { getInt("id") }.use { rows ->
                rows.toList() shouldBe listOf(1, 2, 3)
                shouldThrow<IllegalStateException> { rows.toList() }
            }
        }
    }

    describe("eager select") {
        // This overload used to exist for side effects, was deleted, and every call site kept
        // compiling against the lazy one -- silently doing nothing.
        it("actually visits every row") {
            var seen = 0
            shared.select("SELECT id FROM regress") { seen++ }
            seen shouldBe 3
        }
    }

    describe("transaction integrity") {
        // The commit sat in .onSuccess, outside runCatching, so a failing commit never rolled back
        // and a dirty connection went back to the pool.
        it("rolls back when the commit itself fails") {
            val conn = FailingCommitConnection(shared)
            shouldThrow<SQLException> {
                SingleConnection(conn).transaction { update("UPDATE regress SET name='x' WHERE id=1") }
            }
            conn.rolledBack shouldBe true
        }

        it("rolls back when the body fails") {
            val conn = FailingCommitConnection(shared, failCommit = false)
            shouldThrow<IllegalStateException> {
                SingleConnection(conn).transaction { error("boom") }
            }
            conn.rolledBack shouldBe true
        }

        it("commits and returns a value on success") {
            SingleConnection(shared).transaction { selectFirst("SELECT id FROM regress WHERE id=1") { getInt(1) } }
                .shouldBe(1)
        }
    }

    describe("generated keys") {
        it("returns the key for a single row insert") {
            shared.insertReturnKey("INSERT INTO keyed(name) VALUES(?)", "one").shouldNotBeNull()
        }

        // Reading generatedKeys for a multi-row insert returns one arbitrary key; null means
        // "not exactly one row", which is what callers branch on.
        it("returns null when the insert did not affect exactly one row") {
            shared.insertReturnKey("INSERT INTO keyed(name) SELECT name FROM regress") shouldBe null
        }
    }
})

private class TrackingConnection(private val delegate: Connection) : Connection by delegate {
    private val statements = mutableListOf<PreparedStatement>()

    override fun prepareStatement(sql: String): PreparedStatement =
        delegate.prepareStatement(sql).also { statements += it }

    fun allClosed() = statements.isNotEmpty() && statements.all { it.isClosed }

    override fun close() = Unit // the in-memory connection is shared across the spec
}

private class FailingCommitConnection(
    private val delegate: Connection,
    private val failCommit: Boolean = true,
) : Connection by delegate {
    var rolledBack = false

    override fun commit() {
        if (failCommit) throw SQLException("commit failed") else delegate.commit()
    }

    override fun rollback() {
        rolledBack = true
    }

    override fun setAutoCommit(autoCommit: Boolean) = Unit
    override fun close() = Unit
}

private class SingleConnection(private val conn: Connection) : DataSource by NoopDataSource {
    override fun getConnection(): Connection = conn
}

private object NoopDataSource : DataSource {
    override fun getConnection(): Connection = throw UnsupportedOperationException()
    override fun getConnection(username: String?, password: String?): Connection =
        throw UnsupportedOperationException()

    override fun getParentLogger() = throw UnsupportedOperationException()
    override fun setLogWriter(out: java.io.PrintWriter?) = Unit
    override fun setLoginTimeout(seconds: Int) = Unit
    override fun getLoginTimeout() = 0
    override fun getLogWriter(): java.io.PrintWriter = throw UnsupportedOperationException()
    override fun <T : Any?> unwrap(iface: Class<T>?): T = throw UnsupportedOperationException()
    override fun isWrapperFor(iface: Class<*>?) = false
}
